/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rn9AUqq68cNWSobWHzmBeC

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsaOlWnQtei7WO } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: AOlWnQTEI7wO/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsaOlWnQtei7WO
});
