spring.application.name=broPay-api

# OpenAI
openai.api.key=${OPENAI_API_KEY}

# MongoDB
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.socket-timeout=30000
spring.data.mongodb.connect-timeout=30000
spring.data.mongodb.server-selection-timeout=30000
spring.data.mongodb.retry-writes=true
spring.data.mongodb.retry-reads=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# STRIPE
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.success.url=${STRIPE_SUCCESS_URL}
stripe.cancel.url=${STRIPE_CANCEL_URL}

# Google OCR Credential path
GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
